[package]
name = "kfn-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
dbg_hex = "0.1.1"
rust-ini = "0.18.0"
derivative = "2.2.0"